- hosts: centos
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Apache on CentOS
    yum:
      name: httpd
      state: latest

  - name: Start Apache
    systemd:
      state: started
      enabled: yes
      name: httpd 

  - name: Download Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/finexo.zip
      dest: /tmp/finexo.zip

  - name: Install Unzip
    yum:
      name: unzip
      state: latest

  - name: Extract Template
    unarchive:
      src: /tmp/finexo.zip
      dest: /tmp/
      remote_src: yes   

  - name: Move Template Files
    shell: mv /tmp/finexo-html/* /var/www/html/
    args:
      creates: /var/www/html/index.html



- hosts: ubuntu
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: latest

  - name: Start Apache
    systemd:
      state: started
      enabled: yes
      name: apache2 

  - name: Download Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/browny.zip
      dest: /tmp/browny.zip

  - name: Install Unzip
    apt:
      name: unzip
      state: latest

  - name: Extract Template
    unarchive:
      src: /tmp/browny.zip
      dest: /tmp/
      remote_src: yes   

  - name: Move Template Files
    shell: mv /tmp/browny-v1.0/* /var/www/html/
    args:
      creates: /var/www/html/index.html
